apiVersion: v1
kind: Service
metadata:
  name: rag-app
  labels:
    app: enterprise-rag-platform
spec:
  selector:
    app: enterprise-rag-platform
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
